['editor.asset_browser']
grid_padding = 16.0
thumbnail_size = 64.0
tree_column_width = 150.0

['editor.console']
auto_scroll = true
max_log_lines = 2000
show_location = true
show_thread_name = false
show_timestamp = false

['editor.ui']
font_path = 'CoreAssets://Font/malgun.ttf'
font_size = 17.0

[graphics]
present_mode = 'mailbox'

[performance]
busy_wait_ratio = 0.10000000149011612
target_fps = 240

[window]
borderless = false
fullscreen = false
height = 900
resizable = true
title = 'SimpleEngine'
width = 1600