[graphics]
present_mode = 0

[performance]
busy_wait_ratio = 0.10000000149011612
target_fps = 240

[vfs]
CoreAssets = 'EngineCore/Assets'
CoreShader = 'EngineCore/Shaders'
EditorAssets = 'Editor/Assets'
EditorShader = 'Editor/Shaders'
Logs = 'Logs'

[window]
borderless = false
fullscreen = false
height = 900
resizable = true
title = 'SimpleEngine'
width = 1600